#!/system/bin/sh

echo '270' > /sys/devices/platform/kcal_ctrl.0/kcal_sat

echo 'Y' > /sys/module/workqueue/parameters/power_efficient
echo '1' > /sys/kernel/fast_charge/force_fast_charge
echo 'Y' > /sys/module/adreno_idler/parameters/adreno_idler_active
su -c "iptables -t mangle -A POSTROUTING -j TTL --ttl-set 64"
